apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trade
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
    rules:
        - http:
            paths:
            - path: /strategy
              backend:
                service:
                  name: trade
                  port:
                    number: 80
---
apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Service
metadata:
  name: trade
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector: 
    app: trade
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: trade
spec:
  selector:
    matchLabels:
      app: trade
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: trade
    spec:
      containers:
      - name: trade
        image: emandere/trade-{platform}:{buildId}
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Prodk3s"
        volumeMounts:
          - name: secrets
            mountPath: "/var/www/html/trade/secrets"
            readOnly: true
        ports:
        - containerPort: 80
      nodeSelector:
        platform: {platform}
      volumes:
        - name: secrets
          secret:
            secretName: faccount
